name: Clang-Format
on:
  workflow_call:
jobs:
  clang-format:
    timeout-minutes: 45
    name: Clang-Format
    runs-on: [self-hosted, docker, builder]
    container:
      image: ghcr.io/steinwurf/clang-format-12:1.0.0
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh/root/.ssh
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Run Clang-format
        run: find ./ -iname *.hpp -o -iname *.cpp -o -iname *.c -o -iname *.h | xargs clang-format --dry-run --Werror
